[build-system]
requires = [
    "cython",
    "oldest-supported-numpy",
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "shapely"
dynamic = ["version"]
authors = [
    {name = "Sean Gillies"},
]
maintainers = [
    {name = "Shapely contributors"},
]
description = "Manipulation and analysis of geometric objects"
readme = "README.rst"
keywords = ["geometry", "topology", "gis"]
license = {text = "BSD 3-Clause"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: GIS",
]
requires-python = ">=3.6"
dependencies = [
    "numpy>=1.13",
]

[project.optional-dependencies]
test = ["pytest"]
docs = ["sphinx", "numpydoc"]

[project.urls]
documentation = "https://shapely.readthedocs.io/"
repository = "https://github.com/shapely/shapely"
changelog = "https://github.com/shapely/shapely/blob/main/CHANGELOG.rst"

[tool.setuptools.packages.find]
include = [
    "shapely",
    "shapely.*",
]

[tool.setuptools_scm]
write_to = "shapely/_version.py"

[tool.coverage.run]
source = ["shapely"]
omit = ["shapely/tests/*"]
